# copied from https://github.com/rustasync/tide/blob/master/.travis.yml

language: rust
rust: stable
os: linux
cache: cargo

matrix:
  include:
  - name: cargo doc
    env: [CACHE_NAME=docs]
    script:
    - RUSTDOCFLAGS=-Dwarnings
      cargo doc --all-features --no-deps

  - name: cargo fmt
    cache: false
    before_script: rustup component add rustfmt
    script: cargo fmt -- --check

  - name: cargo clippy
    env: [CACHE_NAME=clippy]
    before_script: rustup component add clippy
    script: cargo clippy --all-targets -- -Dwarnings

  - name: cargo build --no-default-features
    env: [CACHE_NAME=no-default-features]
    script:
    - cargo build --no-default-features

  - name: cargo test
    script: cargo test --verbose

notifications:
  email:
    on_success: never
